[32m2024-11-25 16:10:29.211[0m | [34m[1mDEBUG   [0m | [36mvector_prediction_model.trainer[0m:[36mtrain[0m:[36m107[0m - [34m[1mBeginning training...[0m
[32m2024-11-25 16:10:29.484[0m | [34m[1mDEBUG   [0m | [36mvector_prediction_model.trainer[0m:[36mtrain[0m:[36m152[0m - [34m[1mEpoch: 0, Iteration: 0[0m
[32m2024-11-25 16:10:29.485[0m | [34m[1mDEBUG   [0m | [36mvector_prediction_model.trainer[0m:[36mtrain[0m:[36m153[0m - [34m[1mTrain Loss: 0.7163, Train Acc: 0.5006[0m
[32m2024-11-25 16:10:29.485[0m | [34m[1mDEBUG   [0m | [36mvector_prediction_model.trainer[0m:[36mtrain[0m:[36m156[0m - [34m[1mVal Loss: 0.1431, Val Acc: 0.5014[0m
[32m2024-11-25 16:10:29.485[0m | [34m[1mDEBUG   [0m | [36mvector_prediction_model.trainer[0m:[36mtrain[0m:[36m157[0m - [34m[1mAvg time per iter: 0.2736s[0m
[32m2024-11-25 16:10:29.485[0m | [34m[1mDEBUG   [0m | [36mvector_prediction_model.trainer[0m:[36mtrain[0m:[36m160[0m - [34m[1m
[0m
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/rp/abhay_ws/mujoco_contact_graph_generation/vector_prediction_model/train.py", line 33, in <module>
    main()
  File "/home/rp/abhay_ws/mujoco_contact_graph_generation/vector_prediction_model/train.py", line 29, in main
    trainer.train()
  File "/home/rp/abhay_ws/mujoco_contact_graph_generation/vector_prediction_model/trainer.py", line 165, in train
    self.save_checkpoint(
  File "/home/rp/abhay_ws/mujoco_contact_graph_generation/vector_prediction_model/trainer.py", line 195, in save_checkpoint
    torch.save(state, filename)
  File "/home/rp/miniconda3/envs/peg_in_hole_dm_env/lib/python3.12/site-packages/torch/serialization.py", line 849, in save
    with _open_zipfile_writer(f) as opened_zipfile:
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rp/miniconda3/envs/peg_in_hole_dm_env/lib/python3.12/site-packages/torch/serialization.py", line 716, in _open_zipfile_writer
    return container(name_or_buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rp/miniconda3/envs/peg_in_hole_dm_env/lib/python3.12/site-packages/torch/serialization.py", line 687, in __init__
    super().__init__(torch._C.PyTorchFileWriter(self.name))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Parent directory data/training does not exist.
